export const ZODIAC_SIGNS = [
  {
    id: 'aries',
    name: 'Bélier',
    symbol: '♈',
    element: 'Feu',
    rulingPlanet: 'Mars',
    startMonth: 3,
    startDay: 21,
    endMonth: 4,
    endDay: 19,
    description: 'Le Bélier est le premier signe du zodiaque, symbolisant le renouveau, l\'audace et l\'énergie pure. C\'est un signe d\'action qui n\'hésite pas à foncer tête baissée vers ses objectifs.',
    history: 'Dans la mythologie grecque, le Bélier représente le bélier à la Toison d\'Or qui sauva Phrixos et Hellé. Son sacrifice et son élévation au rang de constellation symbolisent le courage et le dévouement.',
    traits: ['Courageux', 'Déterminé', 'Passionné', 'Impatient', 'Leader'],
    quote: 'L\'audace est le premier pas vers la victoire.',
    compatibleWith: ['leo', 'sagittarius', 'gemini', 'libra'],
    lessCompatibleWith: ['cancer', 'capricorn'],
    compatibilityAnalysis: 'Le Bélier s\'entend merveilleusement avec les autres signes de Feu (Lion, Sagittaire) car ils partagent la même passion. L\'Air (Gémeaux, Balance) attise son feu créatif.'
  },
  {
    id: 'taurus',
    name: 'Taureau',
    symbol: '♉',
    element: 'Terre',
    rulingPlanet: 'Vénus',
    startMonth: 4,
    startDay: 20,
    endMonth: 5,
    endDay: 20,
    description: 'Le Taureau est un signe de stabilité, de patience et de persévérance. Profondément lié à la terre, il apprécie les plaisirs sensoriels et la sécurité matérielle.',
    history: 'Le Taureau est associé au mythe de Zeus se transformant en taureau blanc pour séduire Europe. Il symbolise la force tranquille, la fertilité et la beauté terrestre.',
    traits: ['Fiable', 'Patient', 'Pratique', 'Possessif', 'Gourmand'],
    quote: 'La patience est la clé de la sérénité.',
    compatibleWith: ['virgo', 'capricorn', 'cancer', 'scorpio'],
    lessCompatibleWith: ['leo', 'aquarius'],
    compatibilityAnalysis: 'Le Taureau trouve la paix avec les signes de Terre (Vierge, Capricorne) qui partagent son besoin de sécurité. L\'Eau (Cancer, Scorpion) nourrit sa nature fertile.'
  },
  {
    id: 'gemini',
    name: 'Gémeaux',
    symbol: '♊',
    element: 'Air',
    rulingPlanet: 'Mercure',
    startMonth: 5,
    startDay: 21,
    endMonth: 6,
    endDay: 20,
    description: 'Les Gémeaux sont connus pour leur curiosité insatiable, leur adaptabilité et leur esprit vif. Ils sont les communicateurs du zodiaque, toujours en quête de nouvelles informations.',
    history: 'Représentés par les jumeaux Castor et Pollux, ils symbolisent la dualité humaine, l\'échange entre le mortel et l\'immortel, et la soif de connaissance infinie.',
    traits: ['Curieux', 'Adaptable', 'Sociable', 'Indécis', 'Éloquent'],
    quote: 'La connaissance est le pont entre deux mondes.',
    compatibleWith: ['libra', 'aquarius', 'aries', 'leo'],
    lessCompatibleWith: ['virgo', 'pisces'],
    compatibilityAnalysis: 'Les Gémeaux s\'épanouissent avec les signes d\'Air (Balance, Verseau) pour des échanges intellectuels. Le Feu (Bélier, Lion) stimule leur curiosité naturelle.'
  },
  {
    id: 'cancer',
    name: 'Cancer',
    symbol: '♋',
    element: 'Eau',
    rulingPlanet: 'Lune',
    startMonth: 6,
    startDay: 21,
    endMonth: 7,
    endDay: 22,
    description: 'Le Cancer est un signe profondément intuitif, émotionnel et protecteur. Très attaché au foyer et à la famille, il possède une grande sensibilité et une imagination débordante.',
    history: 'Associé au crabe envoyé par Héra pour distraire Hercule, il symbolise la protection, la ténacité et le lien indéfectible avec les racines et le passé.',
    traits: ['Intuitif', 'Protecteur', 'Sensible', 'Humeur changeante', 'Loyal'],
    quote: 'Le cœur est le foyer de l\'âme.',
    compatibleWith: ['scorpio', 'pisces', 'taurus', 'virgo'],
    lessCompatibleWith: ['aries', 'libra'],
    compatibilityAnalysis: 'Le Cancer fusionne avec les signes d\'Eau (Scorpion, Poissons) dans une compréhension émotionnelle. La Terre (Taureau, Vierge) lui offre la structure dont il a besoin.'
  },
  {
    id: 'leo',
    name: 'Lion',
    symbol: '♌',
    element: 'Feu',
    rulingPlanet: 'Soleil',
    startMonth: 7,
    startDay: 23,
    endMonth: 8,
    endDay: 22,
    description: 'Le Lion est le roi du zodiaque, rayonnant de confiance, de générosité et de charisme. Il aime être au centre de l\'attention et possède un cœur noble et chaleureux.',
    history: 'Représentant le Lion de Némée vaincu par Hercule, il symbolise la force vitale, la royauté et le courage héroïque qui brille comme le soleil.',
    traits: ['Généreux', 'Chaleureux', 'Créatif', 'Arrogant', 'Fier'],
    quote: 'La force du Lion réside dans son cœur.',
    compatibleWith: ['aries', 'sagittarius', 'gemini', 'libra'],
    lessCompatibleWith: ['taurus', 'scorpio'],
    compatibilityAnalysis: 'Le Lion brille avec les signes de Feu (Bélier, Sagittaire) dans une admiration mutuelle. L\'Air (Gémeaux, Balance) alimente son besoin de reconnaissance.'
  },
  {
    id: 'virgo',
    name: 'Vierge',
    symbol: '♍',
    element: 'Terre',
    rulingPlanet: 'Mercure',
    startMonth: 8,
    startDay: 23,
    endMonth: 8,
    endDay: 22,
    description: 'La Vierge est méticuleuse, analytique et dévouée au service des autres. Elle recherche la perfection et l\'ordre dans tout ce qu\'elle entreprend, avec un esprit pratique.',
    history: 'Souvent associée à Astrée, la déesse de la justice, elle symbolise la pureté, le discernement et le lien entre le ciel et la terre par le travail soigné.',
    traits: ['Analytique', 'Précis', 'Modeste', 'Critique', 'Serviable'],
    quote: 'La perfection est dans les détails.',
    compatibleWith: ['taurus', 'capricorn', 'cancer', 'scorpio'],
    lessCompatibleWith: ['gemini', 'sagittarius'],
    compatibilityAnalysis: 'La Vierge s\'accorde avec les signes de Terre (Taureau, Capricorne) pour construire du concret. L\'Eau (Cancer, Scorpion) adoucit son exigence naturelle.'
  },
  {
    id: 'libra',
    name: 'Balance',
    symbol: '♎',
    element: 'Air',
    rulingPlanet: 'Vénus',
    startMonth: 9,
    startDay: 23,
    endMonth: 10,
    endDay: 22,
    description: 'La Balance recherche l\'harmonie, l\'équilibre et la justice. Elle possède un sens inné de l\'esthétique et s\'épanouit dans les relations sociales et les partenariats.',
    history: 'Seul signe représenté par un objet, elle symbolise l\'équilibre cosmique et la justice d\'Astrée. Elle représente la quête de paix et de beauté universelle.',
    traits: ['Diplomate', 'Gracieux', 'Idéaliste', 'Indécis', 'Sociable'],
    quote: 'L\'équilibre est la quête de la Balance.',
    compatibleWith: ['gemini', 'aquarius', 'leo', 'sagittarius'],
    lessCompatibleWith: ['cancer', 'capricorn'],
    compatibilityAnalysis: 'La Balance s\'harmonise avec les signes d\'Air (Gémeaux, Verseau) pour la communication. Le Feu (Lion, Sagittaire) apporte l\'étincelle à son équilibre.'
  },
  {
    id: 'scorpio',
    name: 'Scorpion',
    symbol: '♏',
    element: 'Eau',
    rulingPlanet: 'Pluton',
    startMonth: 10,
    startDay: 23,
    endMonth: 11,
    endDay: 21,
    description: 'Le Scorpion est intense, mystérieux et doté d\'une grande force de caractère. Il n\'a pas peur d\'explorer les profondeurs de l\'âme humaine et possède une intuition perçante.',
    history: 'Associé au scorpion qui tua Orion, il symbolise la transformation, la mort et la renaissance, ainsi que la puissance des émotions cachées.',
    traits: ['Déterminé', 'Passionné', 'Intuitif', 'Jaloux', 'Magnétique'],
    quote: 'La transformation naît des profondeurs.',
    compatibleWith: ['cancer', 'pisces', 'virgo', 'capricorn'],
    lessCompatibleWith: ['leo', 'aquarius'],
    compatibilityAnalysis: 'Le Scorpion trouve la profondeur avec les signes d\'Eau (Cancer, Poissons). La Terre (Vierge, Capricorne) offre un ancrage à ses passions intenses.'
  },
  {
    id: 'sagittarius',
    name: 'Sagittaire',
    symbol: '♐',
    element: 'Feu',
    rulingPlanet: 'Jupiter',
    startMonth: 11,
    startDay: 22,
    endMonth: 12,
    endDay: 21,
    description: 'Le Sagittaire est un explorateur né, épris de liberté, de vérité et d\'aventure. Il possède un optimisme contagieux et une soif constante d\'élargir ses horizons.',
    history: 'Représenté par le centaure Chiron, le plus sage de sa race, il symbolise la quête de sens, la philosophie et le lien entre l\'instinct animal et l\'esprit divin.',
    traits: ['Optimiste', 'Franc', 'Aventureux', 'Impatient', 'Philosophe'],
    quote: 'L\'aventure est la seule vérité.',
    compatibleWith: ['aries', 'leo', 'libra', 'aquarius'],
    lessCompatibleWith: ['virgo', 'pisces'],
    compatibilityAnalysis: 'Le Sagittaire galope avec les signes de Feu (Bélier, Lion) vers l\'aventure. L\'Air (Balance, Verseau) lui offre l\'espace nécessaire à son expansion.'
  },
  {
    id: 'capricorn',
    name: 'Capricorne',
    symbol: '♑',
    element: 'Terre',
    rulingPlanet: 'Saturne',
    startMonth: 12,
    startDay: 22,
    endMonth: 1,
    endDay: 19,
    description: 'Le Capricorne est ambitieux, discipliné et possède un sens aigu des responsabilités. Il gravit les montagnes de la vie avec patience et détermination pour atteindre le sommet.',
    history: 'Représenté par la chèvre de mer, il symbolise la capacité à naviguer tant dans les profondeurs émotionnelles que sur les sommets de la réussite matérielle.',
    traits: ['Discipliné', 'Ambitieux', 'Prudent', 'Pessimiste', 'Patient'],
    quote: 'Le sommet appartient à ceux qui persévèrent.',
    compatibleWith: ['taurus', 'virgo', 'scorpio', 'pisces'],
    lessCompatibleWith: ['aries', 'libra'],
    compatibilityAnalysis: 'Le Capricorne construit avec les signes de Terre (Taureau, Vierge). L\'Eau (Scorpion, Poissons) apporte la fluidité nécessaire à sa structure rigide.'
  },
  {
    id: 'aquarius',
    name: 'Verseau',
    symbol: '♒',
    element: 'Air',
    rulingPlanet: 'Uranus',
    startMonth: 1,
    startDay: 20,
    endMonth: 2,
    endDay: 18,
    description: 'Le Verseau est visionnaire, original et profondément attaché à ses idéaux humanitaires. Il aime sortir des sentiers battus et valorise l\'indépendance et l\'amitié.',
    history: 'Associé au Ganymède, l\'échanson des dieux, il symbolise le versement de la connaissance sur l\'humanité et la rupture avec les traditions obsolètes.',
    traits: ['Original', 'Indépendant', 'Humanitaire', 'Détaché', 'Inventif'],
    quote: 'L\'originalité est le souffle de la liberté.',
    compatibleWith: ['gemini', 'libra', 'sagittarius', 'aries'],
    lessCompatibleWith: ['taurus', 'scorpio'],
    compatibilityAnalysis: 'Le Verseau innove avec les signes d\'Air (Gémeaux, Balance). Le Feu (Bélier, Sagittaire) apporte l\'énergie nécessaire à ses visions futuristes.'
  },
  {
    id: 'pisces',
    name: 'Poissons',
    symbol: '♓',
    element: 'Eau',
    rulingPlanet: 'Neptune',
    startMonth: 2,
    startDay: 19,
    endMonth: 3,
    endDay: 20,
    description: 'Les Poissons sont rêveurs, compatissants et possèdent une grande sensibilité artistique. Ils sont le dernier signe du zodiaque, intégrant les leçons de tous les autres.',
    history: 'Représentant les poissons en lesquels se transformèrent Aphrodite et Éros pour fuir Typhon, ils symbolisent l\'amour universel et la dissolution de l\'ego.',
    traits: ['Compatissant', 'Artistique', 'Intuitif', 'Rêveur', 'Spirituel'],
    quote: 'Le rêve est la réalité de l\'âme.',
    compatibleWith: ['cancer', 'scorpio', 'taurus', 'capricorn'],
    lessCompatibleWith: ['gemini', 'sagittarius'],
    compatibilityAnalysis: 'Les Poissons rêvent avec les signes d\'Eau (Cancer, Scorpion). La Terre (Taureau, Capricorne) leur offre le contenant nécessaire à leur nature océanique.'
  }
];
